KM273_getsAddHC2 = [
    'MV_E12_EEPROM_ROOM_PROGRAM_MODE',
    'MV_E12_EEPROM_TIME_PROGRAM',
    'MV_E12_EEPROM_TIME_PROGRAM_5FRI',
    'MV_E12_EEPROM_TIME_PROGRAM_5FRI_2',
    'MV_E12_EEPROM_TIME_PROGRAM_1MON',
    'MV_E12_EEPROM_TIME_PROGRAM_1MON_2',
    'MV_E12_EEPROM_TIME_PROGRAM_6SAT',
    'MV_E12_EEPROM_TIME_PROGRAM_6SAT_2',
    'MV_E12_EEPROM_TIME_PROGRAM_7SUN',
    'MV_E12_EEPROM_TIME_PROGRAM_7SUN_2',
    'MV_E12_EEPROM_TIME_PROGRAM_4THU',
    'MV_E12_EEPROM_TIME_PROGRAM_4THU_2',
    'MV_E12_EEPROM_TIME_PROGRAM_2TUE',
    'MV_E12_EEPROM_TIME_PROGRAM_2TUE_2',
    'MV_E12_EEPROM_TIME_PROGRAM_3WED',
    'MV_E12_EEPROM_TIME_PROGRAM_3WED_2'
    ]